"""Shared configuration for the repository mining pipeline."""

from __future__ import annotations

import os

BASE_URL = "https://api.github.com"

GITHUB_TOKEN = os.getenv("GITHUB_TOKEN") or os.getenv("GH_TOKEN")

HEADERS = {
    "Accept": "application/vnd.github+json",
}

if GITHUB_TOKEN:
    HEADERS["Authorization"] = f"Bearer {GITHUB_TOKEN}"

# 7.5s between search calls keeps us safely under 10 requests/min
RATE_LIMIT_DELAY = 7.5

LLM_KEYWORDS = [
    "copilot",
    "chatgpt",
    "gpt",
    "cursor",
    "ai generated",
    "ai-generated",
    "generated by",
    "llm",
    "claude",
    "openai",
]
